export const FilteredEvents: string[] = [
    'NNet.Game.SLoadingProgressMessage',
    //'NNet.Replay.Tracker.SPlayerStatsEvent',
    'NNet.Replay.Tracker.SUnitPositionsEvent',

    'NNet.Game.SUserFinishedLoadingSyncEvent',
    'NNet.Game.STriggerSoundLengthSyncEvent',
    'NNet.Game.STriggerMouseMovedEvent',
    'NNet.Game.SCameraUpdateEvent',
    'NNet.Game.STriggerSoundOffsetEvent',
    'NNet.Game.SSelectionDeltaEvent',
    'NNet.Game.SControlGroupUpdateEvent',
    'NNet.Game.SCommandManagerStateEvent',
    'NNet.Game.SCmdUpdateTargetPointEvent',
    //'NNet.Game.SCmdEvent',
    'NNet.Game.SCmdUpdateTargetUnitEvent',
    'NNet.Game.STriggerSoundtrackDoneEvent',
    'NNet.Game.STriggerDialogControlEvent',
    'NNet.Game.STriggerTransmissionCompleteEvent',
    'NNet.Game.STriggerTransmissionOffsetEvent',
    'NNet.Game.STriggerCutsceneEndSceneFiredEvent',
    'NNet.Game.STriggerTargetModeUpdateEvent',
    'NNet.Game.SCommandManagerResetEvent',
   // 'NNet.Game.SHeroTalentTreeSelectedEvent',
   'NNet.Game.STriggerKeyPressedEvent',
   'NNet.Game.SUnitClickEvent',
    //'NNet.Game.SUserOptionsEvent',

    // tmp
    //'NNet.Game.STriggerPingEvent',
   // 'NNet.Replay.Tracker.SUnitBornEvent',
   // 'NNet.Replay.Tracker.SUnitDiedEvent',
   // 'NNet.Replay.Tracker.SUnitOwnerChangeEvent',
   // 'NNet.Replay.Tracker.SUnitTypeChangeEvent',
   // 'NNet.Replay.Tracker.SHeroBannedEvent',
  //  'NNet.Replay.Tracker.SHeroPickedEvent',
   // 'NNet.Replay.Tracker.SStatGameEvent',
// //   'NNet.Replay.Tracker.SUnitRevivedEvent',
//    'NNet.Replay.Tracker.SUpgradeEvent',
 //   'NNet.Replay.Tracker.SPlayerSetupEvent'
];